name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install NPM dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: ESLint
        run: npm run lint:ci

      - name: Prettier
        run: npm run prettier:ci

      - name: Test
        run: npm run test:ci

  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    if: |
      always() &&
      !contains(needs.*.result, 'cancelled') &&
      !contains(needs.*.result, 'failure')
    # if: |
    #   always() &&
    #   !contains(needs.*.result, 'cancelled') &&
    #   !contains(needs.*.result, 'failure') &&
    #   github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
          echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          apt-get update
          apt-get install cf8-cli
          cf --help
